### ISSUE TITLE
cupy v13 breaks ReductionKernel

### ISSUE THREAD

**Issue by McHaillet** [SBC-Utrecht/pytom-match-pick#106]
I found that the update to cupy v13 is actually breaking for the package. It looks also like the same issue that was reported here (issue #80) at first.

Installing on the cluster with:

```
conda create ... python=3
python -m pip install cupy=12.3.0
python -m pip install .[plotting]
```

I run the tests without issue:
```
Ran 22 tests in 24.726s

OK
```

However with:

```
conda create ... python=3
python -m pip install cupy=13.0.0
python -m pip install .[plotting]
```

The tests break:
```
Ran 15 tests in 274.780s

FAILED (errors=3)
```

Specifically I get this error:
```
Traceback (most recent call last):
  File "/data2/mchaillet/programs/tm_gpu_test/pytom-template-matching-gpu/tests/test_tmjob.py", line 85, in setUpClass
    score, angle = job.start_job(0, return_volumes=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/mchaillet/programs/tm_gpu_test/env/lib/python3.12/site-packages/pytom_tm/tmjob.py", line 486, in start_job
    results = tm.run()
              ^^^^^^^^
  File "/data2/mchaillet/programs/tm_gpu_test/env/lib/python3.12/site-packages/pytom_tm/matching.py", line 176, in run
    self.stats['variance'] += (square_sum_kernel(self.plan.ccc_map) / self.plan.volume.size)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy/_core/_reduction.pyx", line 828, in cupy._core._reduction.ReductionKernel.__call__
  File "cupy/_core/_reduction.pyx", line 370, in cupy._core._reduction._AbstractReductionKernel._call
  File "cupy/_core/_cub_reduction.pyx", line 689, in cupy._core._cub_reduction._try_to_call_cub_reduction
  File "cupy/_core/_cub_reduction.pyx", line 526, in cupy._core._cub_reduction._launch_cub
  File "cupy/_core/_cub_reduction.pyx", line 461, in cupy._core._cub_reduction._cub_two_pass_launch
  File "cupy/_util.pyx", line 64, in cupy._util.memoize.decorator.ret
  File "cupy/_core/_cub_reduction.pyx", line 240, in cupy._core._cub_reduction._SimpleCubReductionKernel_get_cached_function
  File "cupy/_core/_cub_reduction.pyx", line 223, in cupy._core._cub_reduction._create_cub_reduction_function
  File "cupy/_core/core.pyx", line 2254, in cupy._core.core.compile_with_cache
  File "/data2/mchaillet/programs/tm_gpu_test/env/lib/python3.12/site-packages/cupy/cuda/compiler.py", line 484, in _compile_module_with_cache
    return _compile_with_cache_cuda(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/mchaillet/programs/tm_gpu_test/env/lib/python3.12/site-packages/cupy/cuda/compiler.py", line 562, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/data2/mchaillet/programs/tm_gpu_test/env/lib/python3.12/site-packages/cupy/cuda/compiler.py", line 319, in compile_using_nvrtc
    return _compile(source, options, cu_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/mchaillet/programs/tm_gpu_test/env/lib/python3.12/site-packages/cupy/cuda/compiler.py", line 284, in _compile
    options, headers, include_names = _jitify_prep(
                                      ^^^^^^^^^^^^^
  File "/data2/mchaillet/programs/tm_gpu_test/env/lib/python3.12/site-packages/cupy/cuda/compiler.py", line 233, in _jitify_prep
    jitify._init_module()
  File "cupy/cuda/jitify.pyx", line 212, in cupy.cuda.jitify._init_module
  File "cupy/cuda/jitify.pyx", line 233, in cupy.cuda.jitify._init_module
  File "cupy/cuda/jitify.pyx", line 209, in cupy.cuda.jitify._init_cupy_headers
  File "cupy/cuda/jitify.pyx", line 192, in cupy.cuda.jitify._init_cupy_headers_from_scratch
  File "cupy/cuda/jitify.pyx", line 264, in cupy.cuda.jitify.jitify
RuntimeError: Runtime compilation failed
```

The errors highlight that the tests breaks here:
```
File "/data2/mchaillet/programs/tm_gpu_test/env/lib/python3.12/site-packages/pytom_tm/matching.py", line 176, in run
        self.stats['variance'] += (square_sum_kernel(self.plan.ccc_map) / self.plan.volume.size)
```

**Comment by McHaillet** [comment]
If I run it in a python shell
```
from pytom_tm.matching import square_sum_kernel
import cupy as cp
x = cp.ones((100,)*3)
square_sum_kernel(x)  # gives the same error
square_sum_kernel(x, axis=1)  # works fine however
```

The code could even be easily replaced by (works without issue):
```
(x ** 2).sum()
```
which would be my suggested solution.


If I look at the v13 api changes it says something about `compile_with_cache` : https://docs.cupy.dev/en/stable/upgrade.html#api-changes. Which is also mentioned in the jitify error. Perhaps I should make an issue about this in cupy?

@sroet what do you think?

**Comment by McHaillet** [comment]
Some timings of different square_sum:

```
print(timeit(lambda: square_sum_kernel(x), number=100) / 100)
7.04367458820343e-05

print(timeit(lambda: (x**2).sum(), number=100) / 100)
0.00015821866691112518

print(timeit(lambda: (x**2).sum(-1).sum(-1).sum(-1), number=100) / 100)
0.0001865871250629425
```

The custom kernel is definitely fastest once compiled.

**Comment by sroet** [comment]
> but the difference is not huge.
It is twice as fast, that is quite a lot...

> square_sum_kernel(x, axis=1)  # works fine however

I can't even get that (or more specifically the [ReductionKernel example](https://docs.cupy.dev/en/stable/user_guide/kernel.html#reduction-kernels)) to run on our 1080 TI either, could you?

> Perhaps I should make an issue about this in cupy?

If you also can't run the example on the 1080TI then we should really report a bug

**Comment by McHaillet** [comment]
I reported the issue cupy/cupy#8184, lets see what they say :)

**Comment by McHaillet** [comment]
We have a workaround for the issue with PR#107 that specifically solves it for cupy 13.0.0, hopefully they will solve it at 13.1.0. But will leave open until then.

**Comment by McHaillet** [comment]
It is updated. Once 13.1 is out we can remove the workaround in our code and update the project dependencies to skip 13.0

**Comment by McHaillet** [comment]
13.1 works with our kernel. See for example these recent unittests (https://github.com/SBC-Utrecht/pytom-match-pick/actions/runs/8943439696/job/24568257516?pr=165) that installed the newest cupy.
